### ISSUE TITLE
Remove (insecure) stock apps

### ISSUE THREAD

**Issue by patcon** [mission-impossible-android/mission-impossible-android#24]
Seems like an ok idea.

- Mail (since we have K9)
- Downloads
- others?

**Comment by SchnWalter** [comment]
I would suggest having something like this in the settings.yaml
```
remove_apps:
  - com.android.email
  - com.android.providers.downloads.ui
  - com.android.providers.downloads
  - jackpal.androidterm
```

And somehow, maybe using a file, expose the data to a script (firstboot.sh?),  where we could loop over these apps and remove them one by one using something like:
```
/system/bin/pm clear com.android.email
/system/bin/pm disable com.android.email
/system/bin/pm uninstall com.android.email
APK=`/system/bin/pm path com.android.email | cut -d : -f 2`
/system/bin/rm -f ${APK}
```

This is related to: Update stock terminal emulator #21 - we first need to remove the Term.apk, and just install another one, but we might need to remove it in the OpenRecoveryScript and not after we added the new APKs from the mia-update.zip

**Comment by patcon** [comment]
ah good call! great idea! `updater-script` seems like the best place, as then the app data creation and optimizations never happen (which happens during the initial boot process).

fwiw, as I understand it, firstboot is hacky, and we should avoid using it where we can. I since it's running during startup when a bunch of other android boot stuff is running, it's prone to race conditions, so we should keep it as small as possible :)

**Comment by patcon** [comment]
Or wait... Can updater-script run other scripts? I guess not... OK, so unless we want to auto-generate `updater-script` (???) then I guess firstboot it is!

**Comment by SchnWalter** [comment]
Here's a list of apps, with file paths from CM-11:
```yaml
- id: com.android.browser
  path: /system/app/Browser.apk
- id: com.android.email
  path: /system/app/Email.apk
- id: com.android.exchange
  path: /system/app/Exchange2.apk
- id: com.android.providers.downloads.ui
  path: /system/app/DownloadProviderUi.apk
- id: com.android.providers.downloads
  path: /system/priv-app/DownloadProvider.apk
- id: jackpal.androidterm
  path: /system/app/Term.apk
```

We can change the `updater-script` for now, and keep the ticket open until we figure out a proper way to do things on first boot (I'll look a bit more over `/init.rc`, but let's hope it doesn't come to that, in order to keep things simple).
```
delete("/system/app/Browser.apk");
delete("/system/app/Email.apk");
delete("/system/app/Exchange2.apk");
delete("/system/app/DownloadProviderUi.apk");
delete("/system/priv-app/DownloadProvider.apk");
delete("/system/app/Term.apk");
```

Are you OK with this? should I commit these?
